Resource api
nirs/sanlock pull request #2
Opened 2019-05-06 11:11 UTC by aabawer

Resource API should only support (path, offset)tuple list

As stated in sanlock help, resource API only accepts [(path,offset),...] input form as resource argument.
In this patch a handle in resource parsing is added and a test for invalid input as well.

2019-05-11 23:07 UTC, nirs requested changes

2019-05-11 23:07 UTC, nirs commented on python/sanlock.c
> +static void __set_value_error(const char* msg, PyObject* obj);
Underscore prefix is reserved for the compiler and standard library, we should not use them.

Instead of adding bad code like the existing one, lets:
- first fix the bad names in the current code, removing the underscore prefix
- add proper name for the new helper

2019-05-11 23:07 UTC, nirs commented on python/sanlock.c
> +            goto exit_fail;
I hoped that we can simplify the if block, but having a minimal change is nice.

2019-05-11 23:07 UTC, nirs commented on python/sanlock.c
> +__set_value_error(const char* msg, PyObject* obj)
"msg" is better named "fmt", since it is a format string, and it should contain a placeholder for obj.

2019-05-11 23:07 UTC, nirs commented on tests/python_test.py
> +    # test parsing resource which is not a list of tuples
The comment should be at the top of the function body.

2019-05-11 23:07 UTC, nirs commented on tests/python_test.py
> +    disks = [path]
We don't need a real path for this test, so we can do:

    disk = ["not a tuple"]

2019-05-11 23:07 UTC, nirs commented on tests/python_test.py
> +        sanlock.write_resource("ls_name", "res_name", disks)
We want to check that the error message includes our bad input:

    assert repr("not a tuple") in e.value

Finally, we need to check that this handles correctly non-asci unicode and encoded strings. We can use parameters to run this tests with many bad values.

Also note that a newline is missing at the end of the file.

2019-05-12 08:09 UTC, aabawer commented on python/sanlock.c
> +static void __set_value_error(const char* msg, PyObject* obj);
suggesting "utils_" prefix.

2019-05-12 08:29 UTC, aabawer commented on python/sanlock.c
> +static void __set_value_error(const char* msg, PyObject* obj);
one trouble at a time :)

2019-05-12 11:34 UTC, closed without merging

2019-05-12 11:34 UTC, aabawer commented
will submit new PR for nirs/py3