Adding constants for Kibibyte, Mebibyte, Gibibyte, etc.
nirs/sanlock pull request #9
Opened 2019-05-12 13:37 UTC by barpavel

Adding constants for Kibibyte, Mebibyte, Gibibyte, Tebibyte, Pebibyte & Exbibyte and using them everywhere in tests.

Signed-off-by: Pavel Bar <pbar@redhat.com>

2019-05-12 15:12 UTC, nirs requested changes
Thanks, looks much nicer now!

2 issues:
- always put the count before the size (e.g. 3 * MiB instead of MiB * 3)
- keep space around *

2019-05-12 15:12 UTC, nirs commented on tests/python_test.py
> +    (sanlock.ALIGN_SIZE[0], 8*KiB),
Missing space:

    8 * KiB

2019-05-12 15:12 UTC, nirs commented on tests/units.py
> +EiB = 1024**6
I don't think we use PiB or EiB, and we will probably never use them.

2019-05-12 15:12 UTC, nirs commented on tests/daemon_test.py
> +    size = MiB * 3
While we fix this we should also change the order to:

    3 * MiB

Which is more natural.

2019-05-13 08:31 UTC, barpavel commented
1) Removed "EiB" constant, decided to leave "PiB" constant just in case we'll need it in some foreseeable future.
2) Changed the order when multiplying constant:
MiB * 3 --> 3 * MiB
3) Added space around multiplication sign constant when multiplying constant:
8*KiB --> 8 * KiB
Note: I decided to NOT add spaces in 2 places where this would not feel natural.
def check_guard(path, size, guard=b"X", **guard_size=4*KiB**):

2019-05-14 20:36 UTC, nirs reviewed
Looks like duplicate of #11.

Please take the typos commit out of this PR.

2019-05-16 15:30 UTC, barpavel commented
Removed the typos commit.

2019-05-16 17:13 UTC, nirs approved these changes
Awesome, thanks!

2019-05-16 17:14 UTC, merged